### ISSUE TITLE
Two methods with the same name and Invalid number of arguments error

### ISSUE THREAD

**Issue by DryginAlexander** [etherscan/writecontract#43]
I have tried to call `transfer(to, value, data)` method of my token contract then there was `Invalid number of arguments to Solidity function` error. 

My contract contains another transfer method `transfer(to, value)` it has only two arguments. So it looks like backend does not handle this case properly.
 
[Check it here](https://ropsten.etherscan.io/address/0x90b20e3f39caf2e5abb01e4ee8b1fc02de2586e6#writeContract).

**Comment by Enigmatic331** [comment]
Hmm. Since we are done with the overhaul of writecontract to web3js v1.2, might be worthwhile to explicitly add the function name + parameters during the function call (https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html#id12) @khairulmax 

Thanks for the report and we will be cracking on this @DryginAlexander!

**Comment by khairulmax** [comment]
@DryginAlexander issue solved. Please try again
